version: "3.9"

services:
  api:
    build: .
    environment:
      - API_ENDPOINT=0.0.0.0:80
      - TIKTOK_APP_ID=
      - TIKTOK_APP_SECRET=
      - TIKTOK_APP_TOKEN=
      - BQ_PROJECT_ID=
      - BQ_DATASET_ID=
      - BQ_AUC_TABLE_ID=
      - BQ_RES_TABLE_ID=
      - JOB_INTERVAL_HOURS=6
      - STATISTIC_DEPTH_DAYS=7
    ports:
      - "8080:80"
